source 'https://github.com/CocoaPods/Specs.git'
# ignore all warnings from all pods
inhibit_all_warnings!
pod 'Parse'
pod 'ParseFacebookUtilsV4','1.7.1'
pod 'ParseUI'
pod 'Stripe'
pod 'Stripe/ApplePay'
pod 'SVProgressHUD'
